### ISSUE TITLE
fatal error while building the RamCloud project

### ISSUE THREAD

**Issue by MheniMerz** [PlatformLab/RAMCloud#11]
i am trying to use RamCloud on Centos,
i've followed the instructions here
 https://ramcloud.atlassian.net/wiki/spaces/RAM/pages/6848614/General+Information+for+Developers
and installed all the dependencies.

but when making the project i get the following error :
/home/mheni/RAMCloud/src/TransportManager.h:19:29: fatal error: boost/foreach.hpp: No such file or directory
 #include <boost/foreach.hpp>

and this is in multiple files ( they are importing a file that does not exist )

any ideas ?

**Comment by fatihky** [comment]
you must install boost libraries. see: http://www.boost.org/

**Comment by yilongli** [comment]
@MheniMerz Can you find out where the boost header files are installed in your system by running, say, `locate boost | fgrep foreach.hpp`? If boost is installed at an unconventional place in your system, you will have to provide them manually for g++.

**Comment by fatihky** [comment]
Here is output that I got from that command.
```
/opt/f/nnmill-dev/TeaFiles.Cpp/Lib/boost/foreach.hpp
/opt/f/nnmill-dev/TeaFiles.Cpp/Lib/boost/test/utils/foreach.hpp
/usr/include/boost/foreach.hpp
/usr/include/boost/test/utils/foreach.hpp
```

**Comment by MheniMerz** [comment]
thank you all for your quick response.

I've tried installing boost following the instructions on their webpage, but i encountered another problem with zlib library that boost depends on.

so i used a simple `sudo yum install boost boost-devel boost-doc ` i think it installed boost successfully 

 now when i build RamCloud i get a different error from gtest
`fatal error: gtest/gtest.h: No such file or directory 
#include <gtest/gtest.h>`

thank you again.

**Comment by MheniMerz** [comment]
ok i have installed gtest following these instructions

[https://github.com/iat-cener/tonatiuh/wiki/Installing-Google-Test-For-Linux](url)

and i don't get the gtest error any more.
