### ISSUE TITLE
protobuf related errors while building RAMcloud

### ISSUE THREAD

**Issue by MheniMerz** [PlatformLab/RAMCloud#12]
i am trtying to get RAMcloud up and running on Centos.
and after dealing with some dependency problems, that you can check here [https://github.com/PlatformLab/RAMCloud/issues/11](url)
i have encoutered  a protobuf related error that looks like this :

> /home/antd/RAMCloud/obj.master/ServerList.pb.h:618:20: error: base class ‘struct google::protobuf::internal::integral_constant<bool, true>’ has a non-virtual destructor [-Werror=effc++]
>  template <> struct is_proto_enum< ::RAMCloud::ProtoBuf::ServerList_Type> : ::google::protobuf::internal::true_type {};

any one had this ?

**Comment by yilongli** [comment]
@MheniMerz This seems like a g++ and/or protobuf version problem. What versions of g++ and protobuf do you use?

**Comment by MheniMerz** [comment]
hey @yilongli thanks for your response,

these are the versions of g++ and protobuf

##g++

> [mheni@localhost ~]$ g++ --version
> g++ (GCC) 4.8.5 20150623 (Red Hat 4.8.5-16)
> Copyright (C) 2015 Free Software Foundation, Inc.

##protobuf

> [antd@localhost ~]$ protoc --version
> libprotoc 2.6.1

**Comment by yilongli** [comment]
Hi @MheniMerz As we documented at https://ramcloud.atlassian.net/wiki/spaces/RAM/pages/6848614/General+Information+for+Developers, the official version of g++ we support is 4.9.x, we don't have the bandwidth to support versions earlier than that. Besides, the problem here appears to be inside protobuf rather than RAMCloud. g++ 5.x should also work although it might need some tweak in the `GNUmakefile`.

**Comment by MheniMerz** [comment]
hy,
i have installed gcc 4.9.3. 
there were some tweeks involved that i want to mention just for documentation purposes :)

1. I had to download the rpm file from [here](https://drive.google.com/open?id=1Pwq1ua80dGM72i7rpDNAIIdfcR1WK-hG)
2. Then install it using rpm command `sudo rpm -Uvh gcc49-c++-4.9.3-1.el6.x86_64.rpm`
3. next i updated the default gcc version used
delete the default gcc file `sudo rm /usr/bin/gcc`
then add it as a symbolic link to the new version `sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc49 20`
now when i run `gcc --version` i get 

> gcc (GCC) 4.9.3
> Copyright (C) 2015 Free Software Foundation, Inc.
> This is free software; see the source for copying conditions.  There is NO
> warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

but i still get the above error, i guess now i'm sure that it's a protobuf error.

if you have any routes that i can explore, that will be very appreciated.
thank you.

**Comment by yilongli** [comment]
Yes, it is likely a protobuf error. I can confirm that we are also using protobuf 2.6.1 on our machines. Do you have multiple versions of protobuf installed on your machine? One thing to try would be to print out where the protobuf header files are included (see https://stackoverflow.com/questions/5834778/how-to-tell-where-a-header-file-is-included-from for some ways to achieve that).

**Comment by MheniMerz** [comment]
i go rid of the protobuf error.
turns out the gcc install i shared before was just a hack and it was not really solving the issue
what i did instead is :

- completely remove gcc4.8 from my system `sudo yum remove --skip-broken gcc`
- install scl `sudo yum install centos-release-scl`
- install [devtoolset-3](http://mirror.centos.org/centos/7/sclo/x86_64/rh/devtoolset-3/) which includes gcc4.9 `sudo yum install devtoolset-3`
- enable the devtoolset `scl enable devtoolset-3 bash`

And that took care of the protobuf error i had :)
thank you for your help.
Mheni.
