### ISSUE TITLE
trouble when starting the coordinator

### ISSUE THREAD

**Issue by MheniMerz** [PlatformLab/RAMCloud#17]
hy all,
i have finally built Ramcloud on **Centos** without any errors  using `make -j12` following [this tutorial](https://ramcloud.atlassian.net/wiki/spaces/RAM/pages/6848614/General+Information+for+Developers)
the output does not show any errors, but it doesn't say successfully built either. you can find the output file [here](https://github.com/MheniMerz/tmp-logfile/blob/master/ramcloud-make-output)
object files and executable were created in the `obj.master` folder as expected.
My problem now is how to start using RamCloud, i'm following the instructions [here](https://ramcloud.atlassian.net/wiki/spaces/RAM/pages/6848532/Setting+Up+a+RAMCloud+Cluster)
this is what i have done so far :
1. starting zookeeper
    * initialize zookeeper : `sudo zookeeper-server-initialize --force` 
    * and this is the output i get :
```
Force enabled, data/txnlog directories will be re-initialized
No myid provided, be sure to specify it in /var/lib/zookeeper/myid if using non-standalone
```
   * Start the zookeeper server : `sudo zookeeper-server start`
   * output : 

```
JMX enabled by default
Using config: /etc/zookeeper/conf/zoo.cfg
Starting zookeeper ... STARTED
```
2. starting the coordinator
   * `obj.master/coordinator -C infrc:host=`hostname -s`,port=11100 -x zk:127.0.0.1:2181`
   * i get this error
```
1518711218.867120094 CoordinatorMain.cc:154 in main ERROR[1]: Fatal error in coordinator at ???: character conversion failed
```
i keep getting this error even when i try a simple `./coordinator --help`
any help ?
thank you.
Mheni.

**Comment by yilongli** [comment]
```character conversion failed``` is an error from the boost library. Can you take a look at the link below?
https://stackoverflow.com/questions/35382902/boost-program-options-throws-character-conversion-failed

It appears that the most common reason for this error is that the boost header files you include and the boost shared library you link against are from different versions of boost.

**Comment by MheniMerz** [comment]
hy @yilongli thank you for your response.
i've been trying to find a way to change the link to the boost libraries, 
I've looked through the GNUmakefile and haven't found any reference to the boost libraries.
is there a specific file where i change the path to `/usr/local/lib` which is where my boost is installed ?
thank you again.

**Comment by MheniMerz** [comment]
actually i just copied all libboost files from `usr/local/lib` to `/lib64` where i guess the gcc was looking for boost
 `sudo cp /usr/local/lib/libboost* /lib64/`
and now i can run the coordinator :)
thank you for your help :)
