### ISSUE TITLE
some puzzles on RAMCloud setup

### ISSUE THREAD

**Issue by baiwfg2** [PlatformLab/RAMCloud#21]
Hi. I compile RAMCloud and it's ok. When `make install`, there're some files generated in `install` folder. In `bin` folder, there're 3 executables files:
```
root@install (master *)$ ls bin
client  coordinator  ensureServers  server
```

What is ensureServers for ? I refer to [https://ramcloud.atlassian.net/wiki/spaces/RAM/pages/6848532/Setting+Up+a+RAMCloud+Cluster](https://ramcloud.atlassian.net/wiki/spaces/RAM/pages/6848532/Setting+Up+a+RAMCloud+Cluster), but part of docs seems obsolete and cannot find anything about `ensureServers`.

I want to make a local cluster, but still don't know how to pass parameter. Could you tell how to setup service locator, how to pass parameter to binaries server/client/coordinator ?

**Comment by yilongli** [comment]
Hi Lewis,

`ensureServers` is just a simple utility tool used by our performance benchmarking scripts (e.g. `scripts/{cluster, clusterperf}.py`) to make sure a given number of master/backup services are up and running before the experiment. It's not intended to be used for setting up a production cluster. The page you refer to contains info about setting up a production cluster.

I am not sure I understand your question on how to pass parameters to binaries? Can you be more specific? To learn more about service locators, please refer to https://ramcloud.atlassian.net/wiki/spaces/RAM/pages/6848545/Service+Locators.

Please let me know if you have more questions.

Best,
Yilong

**Comment by baiwfg2** [comment]
I'm puzzled with some command-line switches.

After starting zookeeper at port 2181,  I start `server` like this:
> ./install/bin/server -L tcp:host=10.110.27.6,port=1101 -x zk:10.110.27.6:2181

log will continuously say :
> 1523792855.448360584 CoordinatorSession.cc:93 in getSession WARNING[8]: Couldn't read coordinator object for cluster main from storage at 'zk:10.110.27.6:2181'

If I don't give zookeeper switch, again log will continuously say :
> 1523793113.120449728 TransportManager.cc:443 in openSessionInternal WARNING[8]: No supported transport found for locator fast+udp:host=0.0.0.0,port=12246

Why do these two cases happend ?

Furthormore I'm upset with log info. First, what does  the number 1523793113.120449728 mean ? It seems meaningless to users. Could I customize the log output format ?
Second, both above warning log continue to output to terminal, which is not friendly. If the problem is fatal, program should throw, if it's not fatal, just printing one message is ok, I think.

By the way, why does program have no configuration file ? I think it's more conveninent than command line

**Comment by cstlee** [comment]
@baiwfg2 Did you start a coordinator as well?  The first log messages says that the server isn't able to find a coordinator that's registered with zookeeper.  The [documentation](https://ramcloud.atlassian.net/wiki/spaces/RAM/pages/6848532/Setting+Up+a+RAMCloud+Cluster) you referred to earlier has information about how to start a coordinator.  The repeated log messages show that the server is still alive but continually trying to find the coordinator.  They should stop once a coordinator is found.

The second log message basically is saying that service locator you provided (or in this case didn't provide and so a default was provided) is in some way not supported (in this case the ip is not valid).

The number at the beginning of each log message is a timestamp.  I don't believe customizing the log output format is possible unless you are willing to modify the source code.

Totally agree that a configuration file could make things be easier; sadly no one in the research group has had time to implement the feature.  If you were interested in contributing the feature, we be happy to take a look at a PR if you send it out way.

Hope this helps.

**Comment by baiwfg2** [comment]
Many thanks. It works. It turns out to be the problem of the starting order. Coordinator first, then server. I'll dig into that and see whether I can contribute some.
