### ISSUE TITLE
the file hierarchy in src folder is confusing

### ISSUE THREAD

**Issue by baiwfg2** [PlatformLab/RAMCloud#22]
Before creating this issue, I took a look at Peter Miller's paper mentioned in GNUmakefile. However, since it's written in 1998, is it still a better way today ? I mean, there're many powerful tools which can conveviently handle the c/c++ building process such as `cmake`, `ninja`, `scons` ? Why isn't RAMCloud using one of them now ? As far as I know, mongo uses scons, scylladb uses ninja, mysql uses cmake.

One big problem of placing many source files in one location is that people are easily confused with which source files contribute to which exectutables. It's not managable I think.

If a patch is created which refactors the dependency files of server , client , and coordinator and placing them into seperate folders, would it be acceptable ?

**Comment by hq6** [comment]
I advocated the initial separation of sources into src, apps, and
nanobenchmarks, so I'm generally in favor of source separation for more
understandable builds, although others on the project will vary in their
opinions.

However, my first thought is that there is enough overlap between these
three binaries that you'd wind up with most of the files in one directory
anyways.
