### ISSUE TITLE
Standalone version of memory allocator

### ISSUE THREAD

**Issue by HaoyuHuang** [PlatformLab/RAMCloud#26]
Hi, 

Do you have a standalone version of the memory allocator? I'm particular interested in its memcached-variance reported in Section 8.6 in "Log-structured Memory for DRAM-based Storage" paper.  https://www.usenix.org/system/files/conference/fast14/fast14-paper_rumble.pdf

Thanks,
Haoyu

**Comment by johnousterhout** [comment]
Hi Haoyu,

If you send me your e-mail address, I'll send you a separate message
containing a version of memcached created by Steve Rumble to make the
measurements in the paper you refer to: this includes RAMCloud's log-style
storage allocator. This work was done by Steve quite a while ago and no one
still at Stanford is familiar enough with it to give you meaningful help.
So, if you have questions or issues, you will have to try and track down
Steve for answers.

Good luck!

-John-

**Comment by HaoyuHuang** [comment]
Thanks a lot! I have sent you an email.
