### ISSUE TITLE
Request for (Very) High Level Status on Two Features + Memory

### ISSUE THREAD

**Issue by rodgarrison** [PlatformLab/RAMCloud#27]
As RAMCloud has evolved over time, where did *this code REPO* land with respect to these features:

- Linearizability: I'm not seeing any references to RIFL in code *here*. And in an early (great) paper, it was pointed out the early architecture didn't quite do full linearizability. Is linearizability in *this code base*?

- Durability: An early RAMCloud paper writes "RAMCloud currently assumes that servers can continue operating for a short period after an impending power failure is detected so that buffered data can be flushed to secondary storage." Therefore RAMCloud actually doesn't do full durability unless (*) there's battery backup for the server rack or per server (*) and/or the data that would be written to disk is first staged to NVM then to disk. Is this where things still stand?

- Memory: Are there any known memory leaks in this code?

Much appreciated.

**Comment by johnousterhout** [comment]
On Thu, Feb 14, 2019 at 8:36 AM rodgarrison <notifications@github.com>
wrote:

> As RAMCloud has evolved over time, where did *this code REPO* land with
> respect to these features:
>
>    -
>
>    Linearizability: I'm not seeing any references to RIFL in code *here*.
>    And in an early (great) paper, it was pointed out the early architecture
>    didn't quite do full linearizability. Is linearizability in *this code
>    base*?
>
>
Yes, linearizability is in the main branch.

**Comment by rodgarrison** [comment]
Much appreciated John. This issue can be closed. 

For those new to RAMCloud, it should be pointed out that the durability question here is limited to power loss. That is, the question does not engage the issue in which data was not flushed to disk because of HW, disk subsystem crash, or power supply failure. In those cases maybe the data shouldn't be trusted even if it got to disk somehow. The question, rather, is how can we reasonably work to get it to disk knowing power-failure is a possibility. 

I suppose this leaves open the smaller question of what RAMCloud does it there's an I/O error writing the data.
