### ISSUE TITLE
Using Python Binding

### ISSUE THREAD

**Issue by haochenpan** [PlatformLab/RAMCloud#30]
Hi all,

I tried to deploy RAMCloud, and I believe I have started a coordinator and a master on a single machine successfully. However, I have some issue using Python binding.

At coordinator:
`obj.master/coordinator -C tcp:host=`hostname -s`,port=11000  -x zk:127.0.0.1:2181`
![image](https://user-images.githubusercontent.com/32943456/58521291-2b186600-818a-11e9-9501-f538efaa6ae0.png)

At master:
`obj.master/server -L tcp:host=`hostname -s`,port=11001 -x zk:127.0.0.1:2181 --totalMasterMemory 16000 -f /dev/sda1 --segmentFrames 100 -r 0`
![image](https://user-images.githubusercontent.com/32943456/58521307-3f5c6300-818a-11e9-9dee-c990fca1a54d.png)

Also, I have the following env variables:
`export LD_LIBRARY_PATH=~/RAMCloud/obj.master/`
`export PYTHONPATH=~/RAMCloud/bindings/python/`

However, at a Python terminal, when I run the fourth line of the script at [https://ramcloud.atlassian.net/wiki/spaces/RAM/pages/6848598/Python+Bindings](url), it gives me the error below, and it won't stop.

![image](https://user-images.githubusercontent.com/32943456/58521432-b85bba80-818a-11e9-901c-b4b22ab05b49.png)

Any help on this issue? Did I setup RAMCloud successfully?

Also, when I check `top`, the server and coordinator always take up 100% CPU each, why is that?

![image](https://user-images.githubusercontent.com/32943456/58521592-15577080-818b-11e9-8948-3899dd454722.png)

Another question, does RAMCloud has a shell interpreter, like Cassandra and Redis?

Best wishes,
Roger

**Comment by yilongli** [comment]
The python binding hasn't been updated in a long time so it may not work anymore. That being said, the problem here seems to be that the python binding is trying to connect using the `fast` transport which is deprecated and removed. You can try to modify https://github.com/PlatformLab/RAMCloud/blob/master/bindings/python/ramcloud.py#L232 to use `basic+udp` or just pass a `serverLocator` argument explicitly in the `connect` method.

RAMCloud is dedicating one thread for network communication and it's busy polling the NIC for incoming traffic so you will see 100% CPU usage at least.

RAMCloud doesn't have a shell interpreter.

By the way, could you tell us why you are trying to deploy RAMCloud? RAMCloud as a research project is finished. And we probably have to stop supporting it at some point (e.g. when all the students who worked on it graduate).

**Comment by haochenpan** [comment]
HI @yilongli,

Thank you for your answer, will try to modify that.

I am glad you asked. Our research group is researching the proper data store for virtualized Network Function. This paper [https://www.usenix.org/system/files/conference/nsdi17/nsdi17-kablan.pdf](url) chose RAMCloud as the data store component, and we are trying to see if we can deploy RAMCloud without Infiniband and how that will be different from Redis and other In-memory data stores.

As you said, RAMCloud is a research project, does that mean no one, based on your best knowledge, is using it in a production setting?

Best wishes,
Roger

**Comment by yilongli** [comment]
Probably no unfortunately.

**Comment by haochenpan** [comment]
Hi @yilongli ,

I tried to modify that line in the code. When I run create_table, it gives me error 18 as below:

```
>>> import ramcloud
>>> c = ramcloud.RAMCloud()
>>> c.connect()
>>> c.create_table("table1")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "ramcloud.py", line 243, in create_table
    self.handle_error(s)
  File "ramcloud.py", line 230, in handle_error
    raise RCException(status)
ramcloud.RCException: RAMCloud error 18
```

Any help? Or do you suggest me to switch to another binding? Java or C?

Best wishes,
Roger

**Comment by yilongli** [comment]
I think Java and C bindings are still working though I have never actually used them.

BTW, you can find RAMCloud RPC error code at https://github.com/PlatformLab/RAMCloud/blob/43198532f7b34a7e41291bfd3c061a8e5de4556f/src/Status.h#L83 So if you are willing to debug this problem yourself, you could find where the exception is thrown by searching the source code for the error code and add a log statement (or use macro `DIE` to crash the server and get a stacktrace) to understand what's going wrong. I imagine that the python binding is simple enough that shouldn't be too hard to fix. It's up to you.

**Comment by haochenpan** [comment]
Hi @yilongli,

Thank you for your help. Python and C bindings both work properly. 

It turns out the reason was that I did not pass the coordinator's full locator in. Instead of doing `basic+udp:host=127.0.0.1,port=11000`, I feed `basic+udp:host=127.0.0.1` in connecting. RAMCloud only detects that around [https://github.com/PlatformLab/RAMCloud/blob/master/src/IpAddress.cc#L69](url) and throws some error right away.

Again, thank you for answering my questions.

Cheers,
Roger
