### ISSUE TITLE
Any progress or testing version for numVClients?

### ISSUE THREAD

**Issue by wangchenghku** [PlatformLab/RAMCloud#31]
Hi RAMCloud developers,

I'm curious if you have a testing version for the client parameter `numVClients` which specifies the number of virtual clients each physical client should simulate. This parameter is extremely useful when the number of available machines is limited.

**Comment by yilongli** [comment]
Hi, can you elaborate your question a bit? What do you mean by a "testing version" for `numVClients`?

**Comment by wangchenghku** [comment]
Hi @yilongli  Thanks for your reply! I found the parameter `numVClients ` is defined but not used in the code. Since the number of physical machines is limited in our cluster, I'm just curious where I can find a version of RAMCloud that has ever implemented this feature?

**Comment by yilongli** [comment]
The `numVClients` is a parameter to the `ClusterPerf` program, which is used to run various performance benchmarks. So it is not a parameter to the RAMCloud server but for a client application. I think what you want is running multiple RAMCloud servers on a single machine? I think that's possible and people used to do that.
