### ISSUE TITLE
Questions on setting up RAMCloud server and client

### ISSUE THREAD

**Issue by zzylol** [PlatformLab/RAMCloud#37]
Dear authors,

Thanks for the great work!
I can successfully start the coordinator using ```./obj.master/coordinator -C tcp:host=`hostname -s`,port=11100```.
However, I met issues when I tried to set up servers according to this document: https://ramcloud.atlassian.net/wiki/spaces/RAM/pages/6848532/Setting+Up+a+RAMCloud+Cluster.
When I use cmd ```sudo obj.master/server -L tcp:host=`hostname -s`,port=1101 --totalMasterMemory 16000 -f /dev/sda4 --segmentFrames 10000 -r 2``` to start the server, it will continue reporting the below message. I am not sure whether there is something wrong. 
```
1641665740.053968046 TransportManager.cc:503 in openSessionInternal WARNING[8]: No supported transport found for locator fast+udp:host=0.0.0.0,port=12246
```

Also, I don't know how to start a client based on this page: https://ramcloud.atlassian.net/wiki/spaces/RAM/pages/6848542/Creating+a+RAMCloud+Client.
When I just run ```./apps/client```, it reports the same warning message
```
1641666078.938049402 TransportManager.cc:503 in openSessionInternal WARNING[1]: No supported transport found for locator fast+udp:host=0.0.0.0,port=12246
```

I also don't know how to connect a server to the coordinator or connect a client to the server/coordinator. 

Could you give some hints/instructions on these questions? Thanks a lot!

**Comment by yilongli** [comment]
Hi Zeying, 

RAMCloud is no longer maintained. I am afraid we can't provide much support if you want to use this project. As for this specific error, you need to avoid the `fast` transport that has been long removed from the code base. Try `tcp` for a starter.

**Comment by zzylol** [comment]
Hi Yilong,

Thanks a lot!
